### ISSUE TITLE
Migrate to DOI github enterprise cloud organization.

### ISSUE THREAD

**Issue by dblodgett-usgs** [DOI-USGS/geoknife#420]
Let's use this issue to track the required migration from USGS-R to USGS. 

As part of this, I think we will also need to create an official public code.usgs.gov repository, a public software release, and a DOI for the official release. 

@jordansread -- do you have any concerns? I plan on housing it in the `water` organization in code.usgs.gov alongside our other public R package code and can take on the IPDS / code.usgs.gov process as I did for sbtools.

**Comment by jordansread** [comment]
Is a public data release needed for this? Otherwise, no, looks good. Thanks for doing this.

**Comment by dblodgett-usgs** [comment]
derp -- I mistyped. Should have read public software release. That just means documentation of the review process for the software through IPDS, unless that was done previously and I can reference that in the request to make a public repository?

**Comment by jordansread** [comment]
We have the 2015 geoknife paper and the CRAN releases, but these pre-date the software approval memo. At the time we were doing code peer review alongside a paper that described the work as a package that would allow us to formally release to CRAN (pkgs w/o papers were kept as provisional at that time). So no, we do not have package review artifacts, other than the peer review done on the PRs on this repo.

**Comment by dblodgett-usgs** [comment]
This is done. Will close this once the package URLs have been updated and a new cran release is out.

**Comment by dblodgett-usgs** [comment]
Done in #429
