### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [DOI-USGS/geoknife#428]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by dblodgett-usgs** [comment]
Right, no problem. Will get them removed soon.

**Comment by dblodgett-usgs** [comment]
Done. https://cran.r-project.org/package=geoknife

![image](https://user-images.githubusercontent.com/1492803/207931832-9740e7db-7ca1-4a26-ba50-71bb2f167ce5.png)

**Comment by rsbivand** [comment]
Excellent, thanks so much!
