### ISSUE TITLE
Jobs not completing, showing as "Process accepted" indefinitely

### ISSUE THREAD

**Issue by flakesw** [DOI-USGS/geoknife#431]
I had a ton of success using geoknife last year, but a colleague and I haven't been able to have a process succeed since he started trying to use geoknife last week, following code I wrote in ~Nov 2021. It seems like we're able to get processes started, but they never progress from there. This is using geoknife 1.6.10, R 4.2.0.

Here's an example from this vignette https://owi.usgs.gov/R/training-curriculum/usgs-packages/geoknife-job/index.html:

```
library("geoknife")
evap_fabric_info <- list(times = as.POSIXct(c("2005-01-01", "2015-01-01")),
                         variables = "et",
                         url = 'https://cida.usgs.gov/thredds/dodsC/ssebopeta/yearly')
evap_fabric <- webdata(evap_fabric_info)

# create stencil
evap_stencil <- webgeom('state::Indiana')

# create knife (which defaults to weighted)
evap_knife <- webprocess()
# find unweighted algorithm
all_algorithms <- query(evap_knife, 'algorithms')
unw_algorithm <- all_algorithms[grep('unweighted', names(all_algorithms))]
# set knife algorithm to unweighted
algorithm(evap_knife) <- unw_algorithm

# create the geojob
evap_geojob <- geoknife(evap_stencil, evap_fabric, evap_knife)
check(evap_geojob)
```

When I check on the job, it invariably looks like this:

```
> check(evap_geojob)
$status
[1] "Process Accepted"

$URL
NULL

$statusType
[1] "ProcessAccepted"
```

As far as I've been able to see, the status never changes for these jobs, and I haven't received any emails with finished jobs. I've tried with datasets on both the cida.usgs.gov server and the northwestknowledge.net server with the same result. I suspect the issue involves the job having a null URL, but I wasn't sure how to troubleshoot past that. The fabric does have an appropriate URL:

```
> evap_fabric
An object of class "webdata":
times: 2005-01-01T00:00:00Z, 2015-01-01T00:00:00Z
url: https://cida.usgs.gov/thredds/dodsC/ssebopeta/yearly 
variables: et
```

I appreciate any advice you might have. 

Thanks,
Sam

**Comment by dblodgett-usgs** [comment]
Hi There -- we've had other reports of this and are working on fixing it up. I'll notify you here when things are back to normal.

**Comment by flakesw** [comment]
Thanks so much!

**Comment by etgay** [comment]
Hello, this has been happening to me as well this past week -- from my own code to the tutorial code. Thanks for looking into it!

**Comment by dblodgett-usgs** [comment]
I think we are back in business, sorry it took a while. Can someone please verify that things are working as expected again?

**Comment by flakesw** [comment]
I'm still getting the same behavior, sorry. Any information I can provide to help troubleshoot?

**Comment by dblodgett-usgs** [comment]
I'm seeing success on our dashboard... https://labs.waterdata.usgs.gov/gdp-process-wps/dashboard You are still just getting process accepted?

**Comment by flakesw** [comment]
Sorry, I edited my comment -- it is working as expected after I started a new R session.

**Comment by flakesw** [comment]
No worries, geoknife has saved me days of work so I'm just glad it's being so well maintained!
